# Generated by Django 6.0.1 on 2026-01-29 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eje_estrategico', models.CharField(max_length=200)),
                ('objetivo', models.TextField()),
                ('indicador', models.TextField()),
                ('nivel_esperado', models.TextField()),
                ('ponderacion', models.FloatField()),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='atencion.pauta')),
            ],
        ),
        migrations.CreateModel(
            name='ConductaSello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducta', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nivel_esperado', models.TextField()),
                ('ponderacion', models.FloatField()),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductas', to='atencion.pauta')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('fortalezas', models.TextField(blank=True, null=True)),
                ('oportunidades_mejora', models.TextField(blank=True, null=True)),
                ('resumen_comentarios', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='atencion.colaborador')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atencion.pauta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaConducta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoevaluacion', models.CharField(blank=True, choices=[('NO_LOGRADO', 'No logrado'), ('LOGRADO', 'Logrado'), ('DESTACADO', 'Destacado')], max_length=20, null=True)),
                ('evaluacion_jefatura', models.CharField(blank=True, choices=[('NO_LOGRADO', 'No logrado'), ('LOGRADO', 'Logrado'), ('DESTACADO', 'Destacado')], max_length=20, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('conducta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atencion.conductasello')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_conductas', to='atencion.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoevaluacion', models.CharField(blank=True, choices=[('NO_LOGRADO', 'No logrado'), ('LOGRADO', 'Logrado'), ('DESTACADO', 'Destacado')], max_length=20, null=True)),
                ('evaluacion_jefatura', models.CharField(blank=True, choices=[('NO_LOGRADO', 'No logrado'), ('LOGRADO', 'Logrado'), ('DESTACADO', 'Destacado')], max_length=20, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_objetivos', to='atencion.evaluacion')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atencion.objetivo')),
            ],
        ),
    ]
