# Generated by Django 6.0.1 on 2026-01-29 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ['nombre'], 'verbose_name': 'Coordinador', 'verbose_name_plural': 'Coordinadores'},
        ),
        migrations.AlterModelOptions(
            name='conductasello',
            options={'ordering': ['id'], 'verbose_name': 'Conducta Sello', 'verbose_name_plural': 'Conductas Sello'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='objetivo',
            options={'ordering': ['id'], 'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivos'},
        ),
        migrations.AlterModelOptions(
            name='pauta',
            options={'verbose_name': 'Pauta', 'verbose_name_plural': 'Pautas'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-anio', '-id'], 'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterModelOptions(
            name='respuestaconducta',
            options={'verbose_name': 'Respuesta Conducta', 'verbose_name_plural': 'Respuestas Conducta'},
        ),
        migrations.AlterModelOptions(
            name='respuestaobjetivo',
            options={'verbose_name': 'Respuesta Objetivo', 'verbose_name_plural': 'Respuestas Objetivo'},
        ),
        migrations.RemoveField(
            model_name='pauta',
            name='version',
        ),
        migrations.AlterUniqueTogether(
            name='respuestaconducta',
            unique_together={('evaluacion', 'conducta')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestaobjetivo',
            unique_together={('evaluacion', 'objetivo')},
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(blank=True, default='Coordinador', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='unidad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='conductasello',
            name='ponderacion',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pauta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='atencion.pauta'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='atencion.periodo'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='ponderacion',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='pauta',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='anio',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='respuestaconducta',
            name='conducta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='atencion.conductasello'),
        ),
        migrations.AlterField(
            model_name='respuestaobjetivo',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='atencion.objetivo'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('colaborador', 'periodo', 'pauta')},
        ),
        migrations.RemoveField(
            model_name='respuestaconducta',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='respuestaobjetivo',
            name='comentario',
        ),
    ]
