# Generated by Django 6.0.1 on 2026-01-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0002_alter_colaborador_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('sede', models.CharField(blank=True, default='Arica', max_length=100)),
                ('area_academica', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='conductasello',
            options={},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='objetivo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pauta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='respuestaconducta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='respuestaobjetivo',
            options={},
        ),
        migrations.RenameField(
            model_name='periodo',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaconducta',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaobjetivo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pauta',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='anio',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='retroalimentacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='score_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pauta',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='respuestaconducta',
            name='cumplimiento',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='respuestaobjetivo',
            name='cumplimiento',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='conductasello',
            name='conducta',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='conductasello',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conductasello',
            name='nivel_esperado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conductasello',
            name='pauta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atencion.pauta'),
        ),
        migrations.AlterField(
            model_name='conductasello',
            name='ponderacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fortalezas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='oportunidades_mejora',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.periodo'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='resumen_comentarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='eje_estrategico',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='indicador',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='nivel_esperado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='objetivo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='pauta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atencion.pauta'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='ponderacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='respuestaconducta',
            name='conducta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.conductasello'),
        ),
        migrations.AlterField(
            model_name='respuestaobjetivo',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.objetivo'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='coordinador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='atencion.coordinador'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='pauta',
        ),
        migrations.RemoveField(
            model_name='respuestaconducta',
            name='autoevaluacion',
        ),
        migrations.RemoveField(
            model_name='respuestaconducta',
            name='evaluacion_jefatura',
        ),
        migrations.RemoveField(
            model_name='respuestaobjetivo',
            name='autoevaluacion',
        ),
        migrations.RemoveField(
            model_name='respuestaobjetivo',
            name='evaluacion_jefatura',
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
