# Generated by Django 6.0.1 on 2026-01-28 15:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('campus', models.CharField(max_length=100, verbose_name='Sede')),
                ('area', models.CharField(max_length=120, verbose_name='Área académica')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_score', models.FloatField(default=0)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desempenho.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target', models.FloatField(verbose_name='Meta')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='desempenho.function')),
            ],
        ),
        migrations.CreateModel(
            name='KPIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor medido')),
                ('score', models.FloatField(default=0)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_results', to='desempenho.evaluation')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desempenho.kpi')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidences/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kpi_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='desempenho.kpiresult')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desempenho.period'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('coordinator', 'period')},
        ),
    ]
